# MAC PREFIX|SCORE|DESCRIPTION

74:4C:A1|50|Lite-On WCBN3510A suspected Flock module
80:30:49|50|Lite-On suspected Flock module

70:C9:4E|80|Known Flock Falcon
3C:91:80|80|Known Flock Falcon
D8:F3:BC|80|Known Flock Falcon
08:3A:88|80|Known Flock Falcon

B8:35:32|80|Known Flock Falcon
14:5A:FC|80|Known Flock Falcon
9C:2F:9D|80|Known Flock Falcon
C0:35:32|80|Known Flock Falcon
94:08:53|80|Known Flock Falcon
E4:AA:EA|80|Known Flock Falcon
F4:6A:DD|80|Known Flock Falcon
F8:A2:D6|80|Known Flock Falcon
24:B2:B9|80|Known Flock Falcon
00:F4:8D|80|Known Flock Falcon
D0:39:57|80|Known Flock Falcon
E8:D0:FC|80|Known Flock Falcon
E0:4F:43|80|Known Flock Falcon
B8:1E:A4|80|Known Flock Falcon
70:08:94|80|Known Flock Falcon
58:8E:81|80|Known Flock Falcon
EC:1B:BD|80|Known Flock Falcon
3C:71:BF|80|Known Flock Falcon
58:00:E3|80|Known Flock Falcon
90:35:EA|80|Known Flock Falcon
5C:93:A2|80|Known Flock Falcon
64:6E:69|80|Known Flock Falcon
48:27:EA|80|Known Flock Falcon
A4:CF:12|80|Known Flock Falcon
82:6B:F2|80|Known Flock Falcon
